import time
import sys
import torch

from router.thalamus import Thalamus
from router.hippocampus import Hippocampus
from network.graph import ConceptGraph
from network.hebbian import HebbianUpdater

def slow_print(text, delay=0.03):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def main():
    print("\n" + "="*60)
    slow_print("🐫 Welcome to CAMEL (MSLM Architecture) Interactive Demo 🐫", 0.04)
    print("="*60)
    print("Initializing the Digital Brain...")
    
    # Initialize the MSLM Components
    domains = ["math", "code", "history", "geography"]
    thalamus = Thalamus()
    
    # Note: Prefrontal Cortex requires actual tokenized inputs and model embeddings, 
    # so we bypass it for this text-only terminal simulation.
    
    hippocampus = Hippocampus(decay_factor=0.7, boost_weight=0.3, switch_threshold=0.6)
    graph = ConceptGraph(domains=domains, alpha=0.2)
    updater = HebbianUpdater(learning_rate=0.1, decay_rate=0.02)
    
    time.sleep(0.5)
    print("[+] Thalamus (Gene Map) ................... Ready")
    print("[+] Hippocampus (Context Memory) .......... Ready")
    print("[+] Concept Graph (Spreading Activation) .. Ready")
    print("[+] Hebbian Learning ...................... Active")
    print("="*60 + "\n")
    
    slow_print("Type 'exit' to quit the simulation.\n", 0.02)
    
    while True:
        try:
            query = input("🧠 You: ")
            if query.lower() in ['exit', 'quit', 'q']:
                print("\nShutting down CAMEL... Goodbye! 🐫")
                break
                
            if not query.strip():
                continue
                
            print("\n" + "-"*50)
            
            # Step 1: Thalamus
            print("1. [Thalamus] Scanning keywords (O(1))...")
            thalamus_hint = thalamus.route(query)
            active_hints = {k: round(v, 2) for k, v in thalamus_hint.items() if v > 0}
            print(f"   => Domain Hints: {active_hints if active_hints else 'None (Ambiguous)'}")
            time.sleep(0.5)
            
            # Step 2: Hippocampus
            print("2. [Hippocampus] Applying context and checking for surprise...")
            contextual_scores = hippocampus.apply_context(thalamus_hint)
            active_context = {k: round(v, 2) for k, v in contextual_scores.items() if v > 0}
            print(f"   => Contextual Scores: {active_context if active_context else 'None'}")
            time.sleep(0.5)
            
            # Step 3: Spreading Activation
            print("3. [Concept Graph] Spreading activation to neighbors...")
            A_t = torch.tensor([contextual_scores[d] for d in domains])
            A_t_spread = graph.spread_activation(A_t, hops=1)
            
            final_activations = {domains[i]: round(A_t_spread[i].item(), 2) for i in range(len(domains))}
            print(f"   => Final Activations: {final_activations}")
            time.sleep(0.5)
            
            # Step 4: Wake up cells
            print("4. [Cells] Waking up specialized models...")
            active_cells = []
            for d, score in final_activations.items():
                if score > 0.2: # Activation Threshold
                    active_cells.append(d)
                    
            if active_cells:
                print(f"   => 🟢 WOKE UP: {', '.join(active_cells).upper()} CELL(S)")
            else:
                print(f"   => 💤 No cells crossed the threshold. Outputting default response.")
            time.sleep(0.5)
            
            # Simulate Hebbian Learning if multiple cells woke up
            if len(active_cells) > 1:
                print("5. [Hebbian Learning] Multiple cells active. Strengthening connections...")
                graph.W = updater.update_weights(graph.W, A_t_spread)
                d1, d2 = active_cells[0], active_cells[1]
                idx1, idx2 = graph.domain_to_idx[d1], graph.domain_to_idx[d2]
                new_weight = graph.W[idx1, idx2].item()
                print(f"   => ⚡ Link ({d1.upper()} <-> {d2.upper()}) strengthened to: {new_weight:.3f}")
            
            # Final output simulation
            print("-" * 50)
            if active_cells:
                print(f"🤖 CAMEL: [Simulated response generated by blending embeddings of {', '.join(active_cells)}]")
            else:
                print(f"🤖 CAMEL: I'm not sure how to answer that based on my current specialized domains.")
            print("\n")
            
        except KeyboardInterrupt:
            print("\n\nShutting down CAMEL... Goodbye! 🐫")
            break

if __name__ == "__main__":
    main()
